# Generated by Django 4.1.2 on 2023-05-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('some_info', models.CharField(max_length=250, verbose_name='Краткое описание')),
                ('full_info', models.TextField(verbose_name='Мероприятие')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
